CREATE TABLE Holidays(
	[Id]		INT				NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name]		NVARCHAR(200)	NULL,
	[Date]		DATE			NOT NULL,
	[CreatedOn]	DATETIME2		NOT NULL DEFAULT GETDATE(),
	[UpdatedOn]	DATETIME2		NOT NULL DEFAULT GETDATE())
