CREATE TABLE LeaveStatusTypes(
	[Id]			INT				NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name]			NVARCHAR(200)	NOT NULL,
	[Code]			NVARCHAR(200)	NOT NULL,
	[CreatedOn]		DATETIME	NOT NULL DEFAULT GETDATE(),
	[UpdatedOn]		DATETIME	NOT NULL DEFAULT GETDATE())
