CREATE TABLE Roles(
	[Id]			INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name]			NVARCHAR(200) NOT NULL,
	[Code]			NVARCHAR(200) NOT NULL,
	[Description]	NVARCHAR(400) NULL,
	[CreatedOn]		DATETIME2 NOT NULL DEFAULT GETDATE(),
	[UpdatedOn]		DATETIME2 NOT NULL DEFAULT GETDATE(),
	CONSTRAINT UK_Roles_Code UNIQUE(Code))
