CREATE TABLE UserRoles(
	[Id]			INT			NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[UserId]		INT			NOT NULL,
	[RoleId]		INT			NULL,
	[CreatedOn]		DATETIME2	NOT NULL DEFAULT GETDATE(),
	[UpdatedOn]		DATETIME2	NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_UserRoles_UserId_Users_Id FOREIGN KEY (UserId) REFERENCES Users(Id),
	CONSTRAINT FK_UserRoles_RoleId_Roles_Id FOREIGN KEY (RoleId) REFERENCES Roles(Id))