CREATE TABLE Users(
	[Id]			INT				NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FirstName]		NVARCHAR(200)	NOT NULL,
	[LastName]		NVARCHAR(200)	NOT NULL,
	[Email]			NVARCHAR(200)	NOT NULL,
	[Password]		NVARCHAR(20)	NULL,
	[ManagerId]		INT				NULL,
	[Department]	NVARCHAR(200)	NULL,
	[IsActive]		BIT				NOT NULL DEFAULT 1,
	[CreatedOn]		DATETIME2		NOT NULL DEFAULT GETDATE(),
	[UpdatedOn]		DATETIME2		NOT NULL DEFAULT GETDATE(),
	CONSTRAINT UK_Users_Email UNIQUE(Email),
	CONSTRAINT FK_Users_ManagerId_Users_Id FOREIGN KEY (ManagerId) REFERENCES Users(Id))
